# Generated by Django 2.2 on 2022-05-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_taken',
            new_name='is_available',
        ),
    ]
