# Generated by Django 2.2 on 2022-05-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220528_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id',
            new_name='book_id',
        ),
    ]
